<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20211218233344" tests="1" file="unittest/loader.py" time="0.026" timestamp="2021-12-18T23:33:45" failures="0" errors="1" skipped="0">
	<testcase classname="unittest.loader._FailedTest" name="unit_tests" time="0.026" timestamp="2021-12-18T23:33:45">
		<error type="ImportError" message="Failed to import test module: unit_tests
Traceback (most recent call last):
  File &quot;c:\users\yashas\anaconda3\lib\unittest\loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;c:\users\yashas\desktop\buy_with_time\build-tool\src\unittest\python\unit_tests.py&quot;, line 1, in &lt;module&gt;
    from src.main.python.users.models import UserModel
ModuleNotFoundError: No module named 'src'
"><![CDATA[Traceback (most recent call last):
  File "c:\users\yashas\anaconda3\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "c:\users\yashas\anaconda3\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "c:\users\yashas\anaconda3\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "c:\users\yashas\anaconda3\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: unit_tests
Traceback (most recent call last):
  File "c:\users\yashas\anaconda3\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "c:\users\yashas\desktop\buy_with_time\build-tool\src\unittest\python\unit_tests.py", line 1, in <module>
    from src.main.python.users.models import UserModel
ModuleNotFoundError: No module named 'src'

]]></error>
	</testcase>
</testsuite>
