
Running tests...
----------------------------------------------------------------------
E
======================================================================
ERROR [0.004s]: unit_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\Python310\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: unit_tests
Traceback (most recent call last):
  File "C:\Python310\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "c:\users\joshi\desktop\buy_with_time\src\unittest\python\unit_tests.py", line 1, in <module>
    from src.main.python.users.models import UserModel
ModuleNotFoundError: No module named 'src'


----------------------------------------------------------------------
Ran 1 test in 0.023s

FAILED (errors=1)

Generating XML reports...
