<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20211216230929" tests="1" file="unittest/loader.py" time="0.004" timestamp="2021-12-16T23:09:29" failures="0" errors="1" skipped="0">
	<testcase classname="unittest.loader._FailedTest" name="unit_tests" time="0.004" timestamp="2021-12-16T23:09:29">
		<error type="ImportError" message="Failed to import test module: unit_tests
Traceback (most recent call last):
  File &quot;C:\Python310\lib\unittest\loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;c:\users\joshi\desktop\buy_with_time\src\unittest\python\unit_tests.py&quot;, line 1, in &lt;module&gt;
    from src.main.python.users.models import UserModel
ModuleNotFoundError: No module named 'src'
"><![CDATA[Traceback (most recent call last):
  File "C:\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\Python310\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: unit_tests
Traceback (most recent call last):
  File "C:\Python310\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "c:\users\joshi\desktop\buy_with_time\src\unittest\python\unit_tests.py", line 1, in <module>
    from src.main.python.users.models import UserModel
ModuleNotFoundError: No module named 'src'

]]></error>
	</testcase>
</testsuite>
